// Mock for @tanstack/react-query
// Auto-generated by self-monitoring loop

export const useQuery = () => ({
  data: null,
  error: null,
  isLoading: false,
  isFetching: false,
  isError: false,
  refetch: () => Promise.resolve(),
});

export const QueryClient = class {};
export const QueryClientProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => children;
